#
# Module manifest for module 'PSAttck'
#
# Generated by: josh.rickard
#
# Generated on: 02/20/2020
#
# Updated on: 01/11/2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'PSAttck.psm1'
    # Version number of this module.
    ModuleVersion = '2.0.0'
    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')
    # ID used to uniquely identify this module
    GUID = 'c21db6e6-a9d5-4b93-80d8-2f1e76e2955f'
    # Author of this module
    Author = 'Josh Rickard'
    # Company or vendor of this module
    CompanyName = 'Swimlane'
    # Copyright statement for this module
    Copyright = '(c) 2022 Swimlane. All rights reserved.'
    # Description of the functionality provided by this module
    Description = 'PSAttck is a PowerShell Module that interacts Mitre ATT&CK Framework'
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @('Class/Classes.ps1')
    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @('PSAttck.Format.ps1xml')
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Get-Attck',
        'Get-AttckActor',
        'Get-AttckDataFiles',
        'Get-AttckMalware',
        'Get-AttckMitigation',
        'Get-AttckTactic',
        'Get-AttckTechnique',
        'Get-AttckTool',
        'Get-PSAttckConfiguration',
        'New-AttckObject',
        'Set-PSAttckConfiguration'
        )
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()
    # Variables to export from this module
    VariablesToExport = '*'
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
             # Tags applied to this module. These help with module discovery in online galleries.
             Tags = @('API', 'PowerShell', 'PowerShellCore', 'ATT&CK', 'Mitre', 'Swimlane')
             # A URL to the license for this module.
             LicenseUri = 'https://github.com/swimlane/PSAttck/blob/master/LICENSE.md'
             # A URL to the main website for this project.
             ProjectUri = 'https://github.com/swimlane/PSAttck'
             # A URL to an icon representing this module.
             # IconUri = ''
             # ReleaseNotes of this module
             ReleaseNotes = 'Updated to the latest version of our ATT&CK Generated Dataset and added new arugment completers'
        } # End of PSData hashtable
    } # End of PrivateData hashtable
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}